---
name: reviewdog
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code.
        uses: actions/checkout@v4
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          reporter: github-pr-review

  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code.
        uses: actions/checkout@v4
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

  Shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code.
        uses: actions/checkout@v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: "."
          pattern: "*.sh"
          exclude: "./.git/*"

  actionlint:
    name: runner / actionlint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
